[package]
name = "recipe-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.27.0"
clap = { version = "4.5.37", features = ["derive", "env"] }
itertools = "0.14.0"
rand = "0.9.1"
