[package]
name = "recipe-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive", "env"] }
csv = "1.3.1"
itertools = "0.14.0"
rand = "0.9.1"
unicase = "2.8.1"
