[package]
name = "recipe-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive", "env"] }
csv = "1.3"
itertools = "0.14"
rand = "0.9"
unicase = "2.8"

[profile.release]
codegen-units = 1
lto = true
strip = true
